import Head from 'next/head';
import styles from './layout.module.css';
import Link from 'next/link';

const name = 'Your Name';
export const siteTitle = 'Colourful Cushions by Ecks';

export default function Layout({ children }) {
  return (
      // <Head>
      //   <title>Create Next App</title>
      //   <meta name="description" content="Generated by create next app" />
      //   <meta name="viewport" content="width=device-width, initial-scale=1" />
      //   <link rel="icon" href="/favicon.ico" />
      // </Head>
      <main className={styles.main}>
        <div className={styles.ecksHeader}>
        <div className={styles.siteTitle}><Link href="/">Colourful Cushions</Link></div>
        <div className={styles.ecks}>by Ecks</div>
        </div>
        <div className={styles.mainContent}>{children}</div>
      </main>
  );
}